name: Call devguard workflow

on:
  push

jobs:
    call-workflow-full:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "l3montree-cybersecurity/projects/github-actions-test-project/assets/github-actions-project"
            scan-type: "full"
        secrets:
            devguard-token: ${{ secrets.DEVGUARD_TOKEN }}    
