name: Call devguard workflow

on:
  push

jobs:
    call-workflow-full:
        uses: l3montree-dev/devguard-action/.github/workflows/devguard-full.yml@main
        with:
            devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
            asset-name: "l3montree-cybersecurity/projects/github-actions-test-project/assets/github-actions-project"
